### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by kafkiano** [simplajs/simplajs.org#6]
### I'm submitting a
- [x] Bug report
- [ ] Feature request

### Description

Cannot install npm packages...

Hi I would love to use ur cms but unfortunately I was not able to create new project as described in documentation. I simply just don't know how to launch simplajs as an npm module. I thought maybe I could use this one and modify it to an boilerplate because I think this would help people to find their way into the structure of this awesome cms. 

But sadly im getting the following error when I install the npm modules:

```
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0h.isfunction@3.0.8 extracted to /home/felix/github/simplajs-boilerplate/node_modules/.staging/lodash.isfunction-e357c3d5 (90ms)
error: pathspec '4.0' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by kafkiano** [comment]
I was able to fix this
